server:
  port: 9090


spring:
  security:
    user:
      name: berkan
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit-strategy-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update